### ISSUE TITLE
Improve the behaviour of Muzei when working offline

### ISSUE THREAD

**Issue by Lurux** [muzei/muzei#715]
*This issue concerns sources that provide a continuous or static stream of images, as opposed to one wallpaper at any single point in time.*

With some sources, Muzei will fail to change the background if it reached the end of the provided wallpapers, or if it is currently offline and no following wallpaper has already been downloaded.

When working offline, I think it would be nice if Muzei falled back to temporarily selecting a random wallpaper among the ones that have already been downloaded from the current source.

**Edit:** Once the end of the list have been reached, Muzei sometimes fails to randomly select a wallpaper when clicking "next" while offline, even if previous wallpapers are still available.

As a further improvement, I think it would be a nice touch to preload a few wallpapers in advance whenever running online, in order to reduce the amount of times this is even necessary :slightly_smiling_face:

**Edit:** Currently, Muzei only preloads the two latest wallpapers from the source. I think it should preload a few of the next images in the slideshow order, and continue advancing until all of them have been shown.

**Comment by ianhanniballake** [comment]
> With some sources, Muzei will fail to change the background if it reached the end of the provided wallpapers, or if it is currently offline and no following wallpaper has already been downloaded

That's not how Muzei works. The 'Next Artwork' button only appears if at least 2 artwork are already downloaded and ready, so by definition there is always another artwork already pre-loaded if that button appears.

> When working offline, I think it would be nice if Muzei falled back to temporarily selecting a random wallpaper among the ones that have previously been downloaded from the current source.

Muzei already switches to a random order after if there's no never before seen artwork available.

> As a further improvement, I think it would be a nice touch if we could preload a few wallpapers in advance whenever running online, in order to reduce the amount of times this is even necessary

As mentioned, Muzei already pre-loads the next artwork available. Each MuzeiArtProvider caches up to the last 100 images for offline usage, so this should already be a relatively rare time for any user who has been using your provider for any length of time. (Note that Auto Advance does not advance while offline, it is only manually going forward that works offline).

**Comment by Lurux** [comment]
> That's not how Muzei works. The 'Next Artwork' button only appears if at least 2 artwork are already downloaded and ready, so by definition there is always another artwork already pre-loaded if that button appears.

Oh ok, I didn't catch that. That's strange; with the source I use, I've sometimes seen this button fail to work, even when other artworks had already been downloaded. :thinking:

> Muzei already switches to a random order after if there's no never before seen artwork available.

That's what I suspected indeed, however I've seen this fail to work as per my response above and my other issue. Could this be a bug on the source's side ?

> As mentioned, Muzei already pre-loads the next artwork available. Each MuzeiArtProvider caches up to the last 100 images for offline usage, so this should already be a relatively rare time for any user who has been using your provider for any length of time. (Note that Auto Advance does not advance while offline, it is only manually going forward that works offline).

That's odd, I haven't seen my source preload images in advance, I'm checking again right now.

This can still be improved regardless, I'll correct my answer:

1. I think Muzei should still auto-advance when offline, at least when there are still some unseen wallpapers preloaded
2. In this case, it would be nice to always preload a few more images, so Muzei can still continue even if it's offline for a short period of time.

Here is the source I use: https://f-droid.org/en/packages/net.ebt.muzei.miyazaki/

Should I update this issue, or close it and create a separate one ?

**Comment by ianhanniballake** [comment]
We've fixed the underlying issue of the 'Next Artwork' button not working.

The pre-loading of a new artwork was working - once the device is online, Muzei would verify that the source has a new image downloaded and ready to be viewed, even when offline. What was happening was that after that new image was seen in Muzei, then there would not be yet another new image that Muzei has never loaded before (in the case where the device is still offline). This would automatically switch Muzei into trying to load a random image.

This is where the issue was - Muzei was trying to prioritize non recent artwork. This would take the set of recent artwork (which, as mentioned previously, goes up to 100 images) and automatically exclude artwork up to half the total number of artwork (in the Muzei Ghibli case, it has ~350 images in total available to Muzei, so Muzei was excluding all 100 of the most recent images). This is was that this did not take into account the offline case, meaning Muzei might be excluding every cached image from a source. This would explain why the 'Next Artwork' button would appear (the source does have more than one cached image available), but doesn't do anything (they were all recent).

Now, Muzei doesn't exclude recent images (whether offline or not), it just iterates through a random ordering of non recent images first and *then* iterating through a random ordering of recent images.

**Comment by Lurux** [comment]
Ahhh ok, thank you the clarifications. Sorry if my issue wasn't very clear when I first posted it, I was only discovering the underlying operation of Muzei.

The explanation make sense. At the time of reporting, I also observed that Muzei preloaded the _latest_ images from my static source, hence "skipping" the non-random viewing of all the other images if advancing offline. Has this been fixed too ? (I can update to the latest version to verify).

> What was happening was that after that new image was seen in Muzei, then there would not be yet another new image that Muzei has never loaded before...

As for this, may I suggest preloading a few more images ? Should I post an issue for this ?

Anyways, that you for fixing :smile:
