### ISSUE TITLE
Decoding the same big image repeatedly

### ISSUE THREAD

**Issue by sunshinelwj** [muzei/muzei#717]
Dear developers,

I developed a tool to detect defects in Android apps that can affect Android app runtime performance.

After analyzing the dynamic execution information of Muzei, I found that Muzei showed the phenomenon of decoding a big image repeatedly: when I set the image of “home screen”, I found that a 2560 * 1600 image was repeatedly decoded several times.

The image is:
![image](https://user-images.githubusercontent.com/79445380/109289446-2e5deb80-7861-11eb-8759-5b5ae9c8f040.png)

The location of decoding the image is:
https://github.com/muzei/muzei/blob/main/android-client-common/src/main/java/com/google/android/apps/muzei/render/ImageLoader.kt
Line: 105

After checking the source code of Muzei, I found that there was no image cache for the repeated decoded image.

Because repeated decoding of a big image will take a lot of unnecessary time and memory overhead.
Adding an image cache may be a good way to avoid this unnecessary resource overhead.

Hoping what I found will help to improve Muzei's runtime performance.

Thanks.

**Comment by ianhanniballake** [comment]
Thanks for posting this issue, but this is the expected behavior for Muzei.

Muzei loads the image multiple times because it generates multiple images with different blurring/dimming/grayscale so as to smoothly animate between them when you double tap your wallpaper. That process only happens once per wallpaper image change - the bare minimum required.
