### ISSUE TITLE
Checking Local folder automatically for new images

### ISSUE THREAD

**Issue by lamyergeier** [muzei/muzei#738]
I periodically transfer some pictures to my android folder which is connected to Muzei. Would be nice if Muzei detects new pictures at least once per day in the local folder and add them automatically. At the moment new pictures in the folder don't show up until refreshed manually.

**Comment by ianhanniballake** [comment]
Muzei already automatically does this - when the Auto Advance moves to the next artwork, Muzei automatically [requests a load of new images](https://github.com/muzei/muzei/blob/8f115620d829a122b42744f220a7cc03918b06f7/android-client-common/src/main/java/com/google/android/apps/muzei/sync/ArtworkLoadWorker.kt#L151), which is exactly what [refresh does](https://github.com/muzei/muzei/blob/8f115620d829a122b42744f220a7cc03918b06f7/main/src/main/java/com/google/android/apps/muzei/browse/BrowseProviderFragment.kt#L109) (calling through to the [same load method](https://github.com/muzei/muzei/blob/8f115620d829a122b42744f220a7cc03918b06f7/android-client-common/src/main/java/com/google/android/apps/muzei/sync/ProviderManager.kt#L91)).

Do you have Auto Advance enabled? Have you already seen all images in Muzei when the Auto Advance triggers (i.e., have you seen every image at least once so that Muzei goes through previously seen images in a random order)?

**Comment by ianhanniballake** [comment]
If you're still running into issues, please contact us at support@muzei.co
